// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvYdAxgX1e_YhrtHJZGz9Z__R3AWD_cBg',
    appId: '1:228406102626:web:49f9eb9b8f5d3d9adfdf3b',
    messagingSenderId: '228406102626',
    projectId: 'igreja-app-base',
    authDomain: 'igreja-app-base.firebaseapp.com',
    storageBucket: 'igreja-app-base.appspot.com',
    measurementId: 'G-50LV1Z7FQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwReW0aoUnk0z-9fDYbMohLFFSvqCyeBw',
    appId: '1:228406102626:android:8395cca7ba799ff0dfdf3b',
    messagingSenderId: '228406102626',
    projectId: 'igreja-app-base',
    storageBucket: 'igreja-app-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsRoH_T78V8KCY37ywx-af7DnYI6k14pI',
    appId: '1:228406102626:ios:761244fe760e63a4dfdf3b',
    messagingSenderId: '228406102626',
    projectId: 'igreja-app-base',
    storageBucket: 'igreja-app-base.appspot.com',
    iosClientId: '228406102626-sk1mpfdjlg1nm2gctqd5s95036p27is6.apps.googleusercontent.com',
    iosBundleId: 'com.example.igrejaApp',
  );
}
